//AUTH
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
//POSTS
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const POST_ERROR = 'POST_ERROR';
export const DELETE_POST = 'DELETE_POST';
export const ADD_POST = 'ADD_POST';
//CATEGORIES
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CATEGORY_ERROR = 'CATEGORY_ERROR';
export const GET_SUBCATEGORY = 'GET_SUBCATEGORY';
export const SUBCATEGORY_ERROR = 'SUBCATEGORY_ERROR';
export const CATEGORY_ID = 'CATEGORY_ID';
export const DESCENDANTS_ID = 'DESCENDANTS_ID';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_CATEGORY_ERROR = 'SET_CATEGORY_ERROR';
export const SET_SUB_CATEGORY = 'SET_SUB_CATEGORY';
export const SET_SUB_CATEGORY_ERROR = 'SET_SUB_CATEGORY_ERROR';
export const GET_CATEGORY_POSTS = 'GET_CATEGORY_POSTS';
export const CATEGORY_POST_ERROR = 'CATEGORY_POST_ERROR';

//USERS
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const PROFILE_ERROR = 'PROFILE_ERROR';
//METRO
export const GET_METROS = 'GET_METROS';
export const METRO_ERROR = 'METRO_ERROR';

//PROFILES
//CHAT
//NOTIFICATION
//MAGAZ
//ALERT
//SNACK
//NEWS
//FAVORITES
//IMAGES
//BANNERS
//HERO
